routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();
   
Route::get('/home', [HomeController::class, 'index'])->name('home');
   
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class)->middleware('permission:role-list');
    Route::resource('users', UserController::class)->middleware('permission:user-list');
    Route::resource('contacts', ContactController::class)->middleware('permission:contact-list');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{

    use HasFactory,SoftDeletes;

    protected $fillable = [
        'name', 'contact', 'email'
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    function __construct()
    {
        $this->middleware('permission:contact-list|contact-create|contact-edit|contact-delete', ['only' => ['index','show']]);
        $this->middleware('permission:contact-create', ['only' => ['create','store']]);
        $this->middleware('permission:contact-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:contact-delete', ['only' => ['destroy']]);
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
    $contacts = Contact::latest()->paginate(5);
    return view('contacts.index',compact('contacts'))
    ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('contacts.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|min:5',
            'contact' => 'required|max:9',
            'email' => 'required|email',
        ]);
        Contact::create($request->all());
        return redirect()->route('contacts.index')->with('success','Contact created successfully.');
    }

    /**
    * Display the specified resource.
    *
    * @param  \App\Contact  $contact
    * @return \Illuminate\Http\Response
    */
    public function show(Contact $contact)
    {
        return view('contacts.show',compact('contact'));
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Contact  $contact
    * @return \Illuminate\Http\Response
    */
    public function edit(Contact $contact)
    {
        return view('contacts.edit',compact('contact'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Contact  $contact
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Contact $contact)
    {
        request()->validate([
            'name' => 'required|min:5',
            'contact' => 'required|max:9',
            'email' => 'required|email',
        ]);
        $contact->update($request->all());
        return redirect()->route('contacts.index')->with('success','contact updated successfully');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Contact  $contact
    * @return \Illuminate\Http\Response
    */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->route('contacts.index')->with('success','Contact deleted successfully');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
   <div class="col-lg-12 margin-tb">
      <div class="pull-left">
         <h2>Add New Contact</h2>
      </div>
      <div class="pull-right">
         <a class="btn btn-primary" href="{{ route('contacts.index') }}"> Back</a>
      </div>
   </div>
</div>
@if ($errors->any())
<div class="alert alert-danger">
   <strong>Whoops!</strong> There were some problems with your input.<br><br>
   <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
   </ul>
</div>
@endif
<form action="{{ route('contacts.store') }}" method="POST">
   @csrf
   <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Name:</strong>
            <input type="text" name="name" class="form-control" placeholder="Name">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Contact:</strong>
            <input type="text" name="contact" class="form-control" placeholder="Contact">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Email:</strong>
            <input type="text" name="email" class="form-control" placeholder="Email">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
         <button type="submit" class="btn btn-primary">Submit</button>
      </div>
   </div>
</form>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
   <div class="col-lg-12 margin-tb">
      <div class="pull-left">
         <h2>Edit Contact</h2>
      </div>
      <div class="pull-right">
         <a class="btn btn-primary" href="{{ route('contacts.index') }}"> Back</a>
      </div>
   </div>
</div>
@if ($errors->any())
<div class="alert alert-danger">
   <strong>Whoops!</strong> There were some problems with your input.<br><br>
   <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
   </ul>
</div>
@endif
<form action="{{ route('contacts.update',$contact->id) }}" method="POST">
   @csrf
   @method('PUT')
   <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Name:</strong>
            <input type="text" name="name" value="{{ $contact->name }}" class="form-control" placeholder="Name">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Contact:</strong>
            <input type="text" name="contact" value="{{ $contact->contact }}" class="form-control" placeholder="Contact">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Email:</strong>
            <input type="text" name="email" value="{{ $contact->email }}" class="form-control" placeholder="Email">
         </div>
      </div>      
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
         <button type="submit" class="btn btn-primary">Submit</button>
      </div>
   </div>
</form>
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
   <div class="col-lg-12 margin-tb">
      <div class="pull-left">
         <h2>Contacts</h2>
      </div>
      <div class="pull-right">
         @can('contact-create')
         <a class="btn btn-success" href="{{ route('contacts.create') }}"> Create New Contact</a>
         @endcan
      </div>
   </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
   <p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
   <tr>
      <th>No</th>
      <th>Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th width="280px">Action</th>
   </tr>
   @foreach ($contacts as $contact)
   <tr>
      <td>{{ ++$i }}</td>
      <td>{{ $contact->name }}</td>
      <td>{{ $contact->contact }}</td>
      <td>{{ $contact->email }}</td>
      <td>
         <form action="{{ route('contacts.destroy',$contact->id) }}" method="POST">
            <a class="btn btn-info" href="{{ route('contacts.show',$contact->id) }}">Show</a>
            @can('contact-edit')
            <a class="btn btn-primary" href="{{ route('contacts.edit',$contact->id) }}">Edit</a>
            @endcan
            @csrf
            @method('DELETE')
            @can('contact-delete')
            <button type="submit" class="btn btn-danger">Delete</button>
            @endcan
         </form>
      </td>
   </tr>
   @endforeach
</table>
{!! $contacts->links() !!}
@endsection

resources/views/contacts/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
   <div class="col-lg-12 margin-tb">
      <div class="pull-left">
         <h2> Show Contact</h2>
      </div>
      <div class="pull-right">
         <a class="btn btn-primary" href="{{ route('contacts.index') }}"> Back</a>
      </div>
   </div>
</div>
<div class="row">
   <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Name:</strong>
         {{ $contact->name }}
      </div>
   </div>
   <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Contact:</strong>
         {{ $contact->contact }}
      </div>
   </div>
   <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Email:</strong>
         {{ $contact->email }}
      </div>
   </div>
</div>
@endsection